spring:
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
  application:
    name: project-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/project-db
    username: postgres
    password: 1990
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

server:
  port: 8082

keycloak:
  realm: cydeo-dev
  auth-server-url: http://localhost:8080/auth
  ssl-required: none
  resource: ticketing-app
  credentials:
    secret: kuacBcR4Lp2y3f90rrrBI8t9zbYJuMO2
  use-resource-role-mappings: true
  bearer-only: true

master:
  user:
    username: admin
    password: admin
  realm: master
  client: master-client


eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: http://localhost:${server.port}/actuator

info:
  application:
    name: project-service
    description: Ticketing Application Project Service



resilience4j:
  circuitbreaker:
    instances:
      user-service:
        baseConfig: default
      task-service:
        baseConfig: default
        waitDurationInOpenState: 20000
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 2
  retry:
    instances:
      user-service:
        baseConfig: default
      task-service:
        baseConfig: default
    configs:
      default:
        maxAttempts: 3
        waitDuration: 200
  ratelimiter:
    instances:
      user-service:
        baseConfig: default
      task-service:
        baseConfig: default
    configs:
      default:
        limitRefreshPeriod: 50
        limitForPeriod: 5
        timeout-duration: 20000